### ISSUE TITLE
Using files as request body

### ISSUE THREAD

**Issue by tpluscode** [hypermedia-app/hypertest#42]
Expanding on #32, it should be possible to use a file as request body. For example, sending a pdf from filesystem

```
Invoke {
  // request
  Header Content-Type "application/pdf"
  
  >>> @test/sample-docs/abstract.pdf
} => {
  // response
}
```

Inspired by this [feature of vuepress](https://v1.vuepress.vuejs.org/guide/markdown.html#import-code-snippets) (except I reversed the `<<<` because I find it pointing in the wrong direction 😉)

**Comment by mchlrch** [comment]
Maybe, the direction of `<<< ` is also somewhat inspired by https://en.wikipedia.org/wiki/Here_document#Here_strings from the shell, denoting input

**Comment by tpluscode** [comment]
> Maybe, the direction of <<< is also somewhat inspired by https://en.wikipedia.org/wiki/Here_document#Here_strings from the shell, denoting input

Mhm all right. we could do the same way then
